# pyproject.toml
[tool.poetry]
name = "data-generator"
<<<<<<< HEAD
version = "0.2.0"
=======
version = "0.3.0"
>>>>>>> release/0.3.0
description = "This repo is for generating data from existing dataset to a file or producing dataset rows as message to kafka in a streaming manner."
authors = ["erkansirin78 <erkansirin78@hotmail.com>", "kayademirs <s.kayademir@gmail.com>", "cemalcici <iecemalcici@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/erkansirin78/data-generator"
repository = "https://github.com/erkansirin78/data-generator"    
keywords = ["streaming", "data", "generator"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.7"
kafka-python = "2.0.2"
pandas = "<=1.4.3"
pyarrow = "^15.0.2"
sqlalchemy = "1.4.41"
psycopg2-binary = "2.9.3"
boto3 = "<=1.24.92"
typer = "^0.10.0"

[tool.poetry.scripts]
datagen = "data_generator.datagen:app"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.4"
pytest = "^8.1.1"
coverage = {extras = ["toml"], version = "^7.4.4"}
pytest-cov = "^4.1.0"
nox = "^2024.3.2"
pytest-mock = "^3.14.0"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["data_generator"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
